/**
 * Nexora contract address registry.
 *
 * Addresses are populated by the deployment tooling (see scripts/deployment)
 * which writes a typed deployment artifact. Until a contract is deployed and
 * recorded, addresses resolve to `undefined` and consumers must render
 * "Coming soon" / "Data unavailable" — never a fabricated address.
 */

export interface DeploymentAddresses {
  nxrToken?: string;
  voteToken?: string;
  voteWrapper?: string;
  airdrop?: string;
  vesting?: string;
  staking?: string;
  governor?: string;
  timelock?: string;
  treasury?: string;
  presale?: string;
  multisig?: string;
}

/**
 * Reads the address registry from a deployment metadata file.
 * The file is generated by the deploy scripts, not hand-maintained.
 */
export function loadAddresses(
  env: string = process.env.NEXT_PUBLIC_APP_ENV ?? 'development',
): DeploymentAddresses {
  const key = env === 'production' ? 'base' : 'baseSepolia';

  // Env vars are the runtime fallback; the canonical source is the JSON
  // deployment artifact produced by scripts/deployment.
  const fromEnv: DeploymentAddresses = {
    nxrToken: process.env.NEXT_PUBLIC_NXR_TOKEN_ADDRESS,
    airdrop: process.env.NEXT_PUBLIC_AIRDROP_CONTRACT_ADDRESS,
    vesting: process.env.NEXT_PUBLIC_VESTING_CONTRACT_ADDRESS,
    staking: process.env.NEXT_PUBLIC_STAKING_CONTRACT_ADDRESS,
    governor: process.env.NEXT_PUBLIC_GOVERNOR_CONTRACT_ADDRESS,
    timelock: process.env.NEXT_PUBLIC_TIMELOCK_ADDRESS,
    treasury: process.env.NEXT_PUBLIC_TREASURY_ADDRESS,
    presale: process.env.NEXT_PUBLIC_PRESALE_CONTRACT_ADDRESS,
    multisig: process.env.NEXT_PUBLIC_MULTISIG_ADDRESS,
    voteToken: process.env.NEXT_PUBLIC_VOTE_TOKEN_ADDRESS,
    voteWrapper: process.env.NEXT_PUBLIC_VOTE_WRAPPER_ADDRESS,
  };

  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const artifact = require(`../../deployments/${key}.deployment.json`);
    return { ...artifact, ...fromEnv };
  } catch {
    return fromEnv;
  }
}
